# Generated by Django 6.0 on 2025-12-09 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='froms', to='core.country')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos', to='core.country')),
            ],
        ),
    ]
